config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :products
  end  
  devise_for :users
  get 'home/index'

  root 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :products
  mount_uploader :avatar, AvatarUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :set_locale

  before_action :set_locale
  def set_locale
  session[:locale] = params[:locale] || session[:locale] || I18n.default_locale
  I18n.locale = session[:locale]
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  # GET /lists
  # GET /lists.json
  def index
    @items = List.where(user_id: @user.id).all
    @lists = @items.paginate(page: params[:page], per_page: 5)
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = @user.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_path(@user, @list), notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_path(@user, @list), notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    private
  def set_user
    @user = User.find(current_user)
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :is_bought, :avatar)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_list

  # GET /products
  # GET /products.json
  def index
    @items = Product.where(list_id: @list.id).all
    @products = @items.paginate(page: params[:page], per_page: 5)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = @list.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to list_product_path(@list, @product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to list_product_path(@list, @product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to list_products_path(@list, @product), notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :quantity)
    end

    private
    def set_list
      @list = List.find(params[:list_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        case level.to_sym
          when :notice then "alert alert-info"
          when :success then "alert alert-success"
          when :error then "alert alert-error"
          when :alert then "alert alert-error"
        end
    end
   
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to t('Projeto'), root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse">
      <div class="navbar-nav">

       <% if user_signed_in? %>
        <%= link_to current_user.email, '#', class: 'nav-item nav-link' %>
       <%end%> 
      </div>
    </div>

      <%= link_to 'pt-BR', root_path(locale: 'pt-BR'), class: 'nav-item nav-link' %>

     <% if user_signed_in? %>
     <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-item nav-link') %>
   <% end %>
  </nav>

  <main class="container" role="main">
   <% flash.each do |key, value| %>
     <div class="<%= flash_class(key) %> alert-dismissible fade show" role="alert">
       <%= value %>
     </div>
   <% end %>

    <%= yield %>
  </main>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f|%>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t('list.name') %><br>
    <%= f.text_field :name, class: 'form-control', :required => true %>
  </div>
  
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar, as: :file, class: 'form-control' %>
  </div>

  <div class="form-check mt-3 mb-3">
    <%= f.check_box :is_bought, class: 'form-check-input' %>
     <%= f.label t('list.is_bought'), class: 'form-check-label' %>
  </div>

  <div class="row mt-2 mb-5">
    <div class="col-md-6">
      <%= link_to t('back'), lists_path(@list), class: 'btn btn-dark btn-block', role: :button %>
    </div>
    <div class="col-md-6">
      <%= f.submit class: 'btn btn-primary btn-block' %>
    </div>
  </div>  
<% end %>

app/views/lists/edit.html.erb
<h1><%= t('editing', name: t('list.title', count: 1)) %></h1>

<%= render 'form' %>

<%= link_to t('show'), @list, class: 'btn btn-info', role: :button %>
<%= link_to t('index'), lists_path, class: 'btn btn-outline-secondary', role: :button %>

app/views/lists/index.html.erb
<h1><%= t('listing', name: t('list.title', count: 2)) %></h1>

<table class="table table-striped table-hover table-sm">
 <thead>
   <tr>
     <th scope="col"><%= t('list.name') %></th>
     <th scope="col"><%= t('list.is_bought') %></th>
     <th scope="col"><%= t('actions') %></th>
   </tr>
 </thead>

 <tbody>
   <% @lists.each do |list| %>
     <tr>
       <td><%= list.name %></td>
       <td><%= list.is_bought %></td>
       <td>
         <div class="btn-group btn-group-sm" role="group">
           <%= link_to t('show'), list, class: 'btn btn-info', role: :button %>
           <%= link_to t('edit'), edit_list_path(list), class: 'btn btn-success', role: :button %>
           <%= link_to t('destroy'), list, method: :delete, data: { confirm: t('confirm_destroy') }, class: 'btn btn-danger', role: :button %>
         </div>        
       </td>
     </tr>
   <% end %>
 </tbody>
</table>
<%= will_paginate @contacts, renderer: BootstrapPagination::Rails %>

<br>

<%= link_to t('new', name: t('list.title', count: 1)), new_list_path, class: 'btn btn-primary', role: :button %>

app/views/lists/new.html.erb
<h1><%= t('new', name: t('list.title', count: 1)) %></h1>

<%= render 'form' %>

<%= link_to t('index'), lists_path, class: 'btn btn-outline-secondary', role: :button %>

app/views/lists/show.html.erb
<h1><%= t('show', name: t('list.title', count: 1)) %></h1>

<div class="row justify-content-center mb-5">
  <%= image_tag(@list.avatar_url, 
    class: 'img-thumbnail', 
    width: '500', 
    height: '500') if @list.avatar? %>
  </div>

<table class="table table-striped table-hover table-dark bg-dark">

 <tr>
   <th scope="row"><%= t('list.name') %>:</th>
   <td><%= @list.name %></td>
 </tr>
 <tr>
   <th scope="row"><%= t('list.is_bought') %>:</th>
   <td><%= @list.is_bought %></td>
 </tr>

</table>
<%= link_to t('list.products'), list_products_path(@list), class: 'btn btn-outline-secondary', role: :button %>
<%= link_to t('edit'), lists_path(@list), class: 'btn btn-primary', role: :button %>
<%= link_to t('index'), lists_path, class: 'btn btn-outline-secondary', role: :button %>

app/views/products/_form.html.erb
<%= form_for([@list, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control', :required => true %>
  </div>
  
  <div class="form-group">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity, class: 'form-control', :required => true %>
  </div>

  <div class="row mt-2 mb-5">
    <div class="col-md-6">
      <%= link_to t('back'), list_path(@list), class: 'btn btn-dark btn-block', role: :button %>
    </div>
    <div class="col-md-6">
      <%= f.submit class: 'btn btn-primary btn-block' %>
    </div>
  </div> 
<% end %>

app/views/products/edit.html.erb
<h1><%= t('editing', name: t('product.title', count: 1)) %></h1>

<%= render 'form' %>

<%= link_to t('show'), list_products_path(@list, @product), class: 'btn btn-info', role: :button %>
<%= link_to t('index'), list_products_path(@list), class: 'btn btn-outline-secondary', role: :button %>

app/views/products/index.html.erb
<h1><%= t('listing', name: t('list.product.title', count: 2)) %></h1>

<table class="table table-striped table-hover table-sm">
 <thead>
   <tr>
     <th scope="col"><%= t('list.product.name') %></th>
     <th scope="col"><%= t('list.product.quantity') %></th>
     <th scope="col"><%= t('actions') %></th>
   </tr>
 </thead>

 <tbody>
   <% @products.each do |product| %>
     <tr>
       <td><%= product.name %></td>
       <td><%= product.quantity %></td>
<td>
         <div class="btn-group btn-group-sm" role="group">
           <%= link_to t('show'), list_product_path(@list, product), class: 'btn btn-info', role: :button %>
           <%= link_to t('edit'), edit_list_product_path(@list, product), class: 'btn btn-success', role: :button %>
           <%= link_to t('destroy'), list_product_path(@list, product), method: :delete, data: { confirm: t('confirm_destroy') }, class: 'btn btn-danger', role: :button %>
         </div>
       </td>
     </tr>
   <% end %>
 </tbody>
</table>
  <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
<br>

<%= link_to t('new', name: t('product.title', count: 1)), new_list_product_path(@list), class: 'btn btn-primary', role: :button %>
<%= link_to t('back'), lists_path(@list), class: 'btn btn-secondary', role: :button %>

app/views/products/new.html.erb
<h1><%= t('new', name: t('product.title', count: 1)) %></h1>

<%= render 'form' %>

<%= link_to t('index'), list_products_path(@list), class: 'btn btn-outline-secondary', role: :button %>

app/views/products/show.html.erb
<h1><%= t('listing', name: t('list.product.title', count: 2)) %></h1>

<table class="table table-striped table-hover">

 <tr>
   <th scope="row"><%= t('list.product.name') %>:</th>
   <td><%= @product.name %></td>
 </tr>
 <tr>
   <th scope="row"><%= t('list.product.quantity') %>:</th>
   <td><%= @product.quantity %></td>
 </tr>

</table>

<%= link_to t('edit'), edit_list_product_path(@list, @product), class: 'btn btn-primary', role: :button %>
<%= link_to t('index'), list_products_path(@list), class: 'btn btn-outline-secondary', role: :button %>